version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/lol
hooks:
  BeforeInstall:
    - location: install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: start.sh
    
